### ISSUE TITLE
Not a valid authentication token barcode

### ISSUE THREAD

**Issue by hexcollective** [minagerges/MODX-GoogleAuthenticatorX#11]
When I scan the code with Google Authenticator on iPhone 6+ I get an error message:

The barcode 'otpauth://totp/admin2::http://abc.com/manager/?secret=GX43RANDOM&issuer=MODx Revolution' is not a valid authentication token barcode.

**Comment by minagerges** [comment]
I assume you hit an iPhone issue, in which it doesn't like spaces in the URI.
Change "Site name" in modx settings to a string with no spaces and it should work, but you will have to regenerate the secret to get the new compatible URI (That's an issue within my code)

Please feedback with your outcomes.

**Comment by hexcollective** [comment]
Thanks Mina, indeed editing the site_name fixed the issue.
What are your thoughts on working around the issue, omit title (most 2FA sites I have used don't pre-populate a title) or use &nbsp; perhaps?

**Comment by minagerges** [comment]
Practically a real fix would be from the mobile app side.

From my side this is related to issue #9. Issuer parameter is <a href="https://code.google.com/p/google-authenticator/wiki/KeyUriFormat#Issuer" target="_blank">strongly recommended</a> to be used by Google.

**Comment by hexcollective** [comment]
Yes you're right of course. It should be fixed by Google.
No worries, I can work around this for now.

**Comment by minagerges** [comment]
Marked with priority to be included in next release.
