### ISSUE TITLE
Courtesy login is confusing with extra popup

### ISSUE THREAD

**Issue by Lefthandmedia** [minagerges/MODX-GoogleAuthenticatorX#21]
Hi,

 The 1-time courtesy login is a bit confusing because of the extra popup stating my session expired and i need to login, again.
![Google ChromeScreenSnapz007](https://user-images.githubusercontent.com/3350108/65155975-88347200-da2e-11e9-8124-ec9222b437d4.png)
My guess is this happens because upon giving the QRcode the user is immediatly logged out. Imho that is not necessary.

**Comment by minagerges** [comment]
Please check the [wiki](https://github.com/minagerges/MODX-GoogleAuthenticatorX/wiki) After installing section, point 7.

> If you have courtesy login enabled (Best way to provide the secret) if you refresh the page you will be provided with the same QR-code and will be logged out instantly, if you did not perform steps 1 to 5 earlier, you will have only 60 seconds to scan that qr-code

This occurs because the page attempts a communication, after the user has been logged out.

**Comment by Lefthandmedia** [comment]
yes but my point is ;why do you log the user out? isn't it better to log the user out AFTER he has seen the QR code and has a change to scan it with his phone/app?

**Comment by minagerges** [comment]
This is by design, will not change.
