### ISSUE TITLE
Extra is also working with Microsoft Authenticator App 

### ISSUE THREAD

**Issue by achterbahn** [minagerges/MODX-GoogleAuthenticatorX#27]
As the underlaying process is the same I tested this extra with the Microsoft Authenticator app on Android. 
And it works flawlessly. 

Tested on: 
- Android Device (Samsung S22)
- MODX 2.8.6-pl

Could be useful, if this Extra mentions this compatibility (or even change its name).

**Comment by phantomphondler** [comment]
anyone got this to work on modx 3?

**Comment by minagerges** [comment]
Thank you for reporting. There are tens of application compatible with the used protocol, don't have to mention them all,
Also the name will not change.
