### ISSUE TITLE
Store / generate QR-codes locally

### ISSUE THREAD

**Issue by minagerges** [minagerges/MODX-GoogleAuthenticatorX#6]
Store QR-code locally.A
Create QR-codes locally instead of depending on Google API!!

**Comment by minagerges** [comment]
Cancelled

**Comment by michael-henry-springbok** [comment]
Hello,

It appears that the Google API is finally stopping working. It is now displaying a '502 bad gateway' error for the request to chart.googleapis.com.

If this enhancement is cancelled, could you release an update to GoogleAuthenticatorX using a new QR code generation API? Maybe something like this: https://hub.openapihub.com/en-us/v/open-image-lab-74old/api/qr-code-generator-o8ec6/readme

Thank you!

**Comment by muzzwood** [comment]
@michael-henry-springbok There's a new alternative: https://github.com/Jako/TwoFactorX
